### ISSUE TITLE
In my kali Linux error 

### ISSUE THREAD

**Issue by Brabhu12345** [Gameye98/Lazymux#126]
┌──(root㉿localhost)-[~/Lazymux]
└─# python3 lazymux.py
Traceback (most recent call last):
  File "/root/Lazymux/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/root/Lazymux/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
              ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Brabhu12345** [comment]
How to solve this error

**Comment by Gameye98** [comment]
im sorry but lazymux is only support with termux environment
you may face some issue and conflict because there is lot of difference of package name between kali and termux

in your issues it causes by how termux named python3 package as python by default
but in kali python3 called exactly how it is, and python2 set as python by default

i recommend u to using katoolin which is specifically built for kali

https://github.com/LionSec/katoolin

**Comment by Brabhu12345** [comment]
Thanks 😊👍
