### ISSUE TITLE
when i execute command python2 lazymux.py then showing this error

### ISSUE THREAD

**Issue by blackeyeguest** [Gameye98/Lazymux#25]
![WhatsApp Image 2020-02-20 at 7 34 29 PM](https://user-images.githubusercontent.com/31789494/74941130-86753d00-5418-11ea-896e-9dcca9330509.jpeg)

**Comment by Gameye98** [comment]
you should run lazymux.py with python3

`python lazymux.py`

**Comment by redflag10** [comment]
Nice it work now

**Comment by harie112** [comment]
Kalau begini bagaimna
bash-5.0$ python3 lazymux.py
  File "lazymux.py", line 380                                                           SyntaxError: Non-UTF-8 code starting with '\xae' in file lazymux.py on line 380, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details                 bash-5.0$

**Comment by Gameye98** [comment]
@harie112 coba update tool Lazymux nya

$ cd Lazymux
$ git pull .

**Comment by deepdarksa** [comment]
![Screenshot_20220707-060045_Termux.jpg](https://user-images.githubusercontent.com/47797245/177681484-4fd305ea-dddf-4910-bf1d-357740022a35.jpg)

It needs python and I already have python3
Still need python because when I run python lazymux.py
It doesn't work and says already have python3
Then do the python3 lazymux.py
Got the error 
Any help

**Comment by Gameye98** [comment]
@deepdarksa its only works on termux environment

**Comment by pussyknit** [comment]
Try python instead of python2
