### ISSUE TITLE
How to use Lazymux.apk?

### ISSUE THREAD

**Issue by binuzz** [Gameye98/Lazymux#58]
How to use Lazymux.apk

**Comment by yikikikgumball001** [comment]
codes:
"apt update"
"apt upgrade"
"pkg install python2"
"pkg install git"
"git clone 
https://github.com/Gameye98/Lazymux.git"
"cd"
"ls"
"cd Lazymux"
"ls"

"apt install python git "
"git clone https://github.com/Gameye98/Lazymux"
"cd Lazymux"
"python layzmux.py"

After logging into layzmux, choose your download according to the job you are going to do, for example: if you are going to do a ddos ​​attack, first enter the webhacking and select sqlamp, you can find the ddos ​​attack codes from spyhackerz or instead of lazymux, use the data in github, you will do a little better job with the tools.

**Comment by Gameye98** [comment]
Just use it as usual, install APK file then you can download tools from it, you can check Lazymux path on /sdcard/Lazymux

**Comment by Gameye98** [comment]
If you looking for DoS Attack Tools just go to the Stress Testing...
