### ISSUE TITLE
The tool not Working As Normal!

### ISSUE THREAD

**Issue by ZulTheDev** [Gameye98/Lazymux#69]
Hello there, I'm ZulTheDev and I want to highlighted an Unexpected experience About Lazymux. I was Testing this code for quick A while on my termux app and When I try to re-install After My factory reset It got an error occur the Code did not know what option I was writing on. I install everything back but it seem like the "set_install" is not In the right place and I Come Into error that The "set_install" only And I Would like to hear back from you😊 Thank you for your time!

**Comment by Habibmostafa2002** [comment]
Hello welcome to my world thank you for care about thet you can chat me in
whatsapp cake my number +249901083730
🔚✔

بتاريخ ٢٠٢١/٠٢/١٧ ١٢:١٥ ص، كتب "Zul" <notifications@github.com>:

Hello there, I'm ZulTheDev and I want to highlighted an Unexpected
experience About Lazymux. I was Testing this code for quick A while on my
termux app and When I try to re-install After My factory reset It got an
error occur the Code did not know what option I was writing on. I install
everything back but it seem like the "set_install" is not In the right
place and I Come Into error that The "set_install" only And I Would like to
hear back from you😊 Thank you for your time!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gameye98/Lazymux/issues/69>, or unsubscribe

**Comment by Gameye98** [comment]
In part of set_install you just need to input the number of tool you want to install ...
