### ISSUE TITLE
Ubuntu in termux line 77 syntax issue 

### ISSUE THREAD

**Issue by LAZY-VAMPIRE** [Gameye98/Lazymux#76]
![Screenshot_2021-04-23-20-45-17-030_com termux](https://user-images.githubusercontent.com/82246674/115892845-327b4380-a475-11eb-9cde-e9f3c1dae3c1.jpg)

**Comment by Gameye98** [comment]
It is caused by package naming in ubuntu and termux is different...

package python 2.x in ubuntu named as `python`
package python 3.x in termux named as `python`

You should run Lazymux from termux itself without any other linux environment...

If you still gonna keep up with the ubuntu in termux, check the remake project of Lazymux from the contributor

Try this [Sanix-Darker/Lazymux](https://github.com/Sanix-Darker/Lazymux)
