### ISSUE TITLE
Another session 

### ISSUE THREAD

**Issue by Yisus7u7** [Gameye98/Lazymux#79]
Interesting your installer of things but, you can not add anything else apart from hacking tools?, I am a programmer and I would like a catalago to install useful tools for this, for example to run servers or compile things 

Pd : I use termux with x11-repo 

![Screenshot_20210529-144018](https://user-images.githubusercontent.com/64093255/120557608-cec52e00-c3c3-11eb-84a8-ee51f47ea90a.png)

**Comment by Gameye98** [comment]
The reason for "hacking tools > programmer tools" is because termux is not capable to do that...
Hacking tools usually need small requirements than for programming tools...

I cant even install pandoc, calibre, pyrasite, etc, without changing to other distro and Lazymux is focused only on termux not other linux distros.
If you still want the tool you're searching for... make tools request on xeffyr termux-packages repo... maybe they can find away for this ^^

**Comment by Gameye98** [comment]
Check section issues on this repo and make your own package request

https://github.com/termux/termux-packages

**Comment by Yisus7u7** [comment]
No me entendiste, y bueno lo que acabas de decir es al revez, igual gracias

**Comment by Gameye98** [comment]
Lo siento si no te entiendo, pero termux tiene limitaciones, estoy muy agradecido por abordar este problema.

**Comment by Yisus7u7** [comment]
En eso tienes razón, termux tiene limitaciones pero más en el área del hacking que el de la programación....

**Comment by Yisus7u7** [comment]
Mejor haré yo mismo un instalador, gracias por tu tiempo

:v y por si te sirve te dejo como instalar el desktop de termux de la captura de pantalla de arriba : 

https://github.com/Yisus7u7/termux-desktop-xfce
